AWSTemplateFormatVersion: '2010-09-09'
Description: >-
   Project Carnation : CFN Template to create am IAM Role for Lambda Function and State Machine

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Carnation
  Modification History:
    - 1.0.0  - May 09, 2023  -- Initial Version 
    - 1.0.1  - Jul 23, 2023  -- Added CloudWatch Log access by the State Machine
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
        - ProjectName
        - Environment
    #################################### KMS Key ###################################################
    - Label: 
        default: "KMS Configuration:"
      Parameters: 
      - KmsMasterKeyId
    #################################### Lambda Function ###########################################
    - Label:
        default: "Service Names:"
      Parameters:
      - LambdaFunctionOneBaseName
      - LambdaFunctionTwoBaseName
      - LambdaExecutionRoleBaseName
      - LambdaExecutionPolicyBaseName
    #################################### DynamoDB Table ############################################
    - Label: 
        default: "DynamoDB Configuration:"
      Parameters: 
      - DynamoDBTableBaseName
    #################################### SNS Topic #################################################
    - Label: 
        default: "SNS Topic:"
      Parameters: 
        - SNSTopicBaseName
    #################################### SQS Queue #################################################
    - Label: 
        default: "SQS Queue:"
      Parameters: 
        - SQSQueueBaseName
    #################################### Step Function #############################################
    - Label:
        default: "Step Function:"
      Parameters:
      - StepFunctionExecutionRoleBaseName
      - StepFunctionExecutionPolicyBaseName
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## Lambda Function ###########################################
      LambdaFunctionOneBaseName: 
        default: "Processing Lammba Function Name."
      LambdaFunctionTwoBaseName: 
        default: "Processing Lammba Function Name."
      LambdaExecutionRoleBaseName: 
        default: "Lambda Function Execution Role Name."
      LambdaExecutionPolicyBaseName:
        default: "Lambda Function Execution Policy Name."
      ################################## DynamoDB Table ############################################
      DynamoDBTableBaseName: 
        default: "DynamoDB Table."
      ################################## SNS Topic #################################################
      SNSTopicBaseName:
        default: "SNS Topic."
      #################################### SQS Queue ###############################################
      SQSQueueBaseName:
        default: "SQS Queue."
      ################################## Step Function #############################################
      StepFunctionExecutionRoleBaseName: 
        default: "Step Function Execution Role Name."
      StepFunctionExecutionPolicyBaseName: 
        default: "Step Function Execution Policy Name."
      # StepFunctionName: 
      #   default: "The Name Of The Step Function"
Parameters:
  ################## Project Name and Environment ###############################################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "e4c733c5-9fbe-4a90-bda1-6f0362bc9b89"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 36
    MaxLength: 36
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."
  ##################################### Lambda Function ###########################################
  LambdaFunctionOneBaseName:
    Default: some-lambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: "Must be between 10 and 40 characters long and begin with a letter and can contain number or hyphen (-)."
  LambdaFunctionTwoBaseName:
    Default: some-other-ambda-function-name
    Description: Processing Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: "Must be between 10 and 40 characters long and begin with a letter and can contain number or hyphen (-)."
  LambdaExecutionRoleBaseName:
    Default: lambda-function-role-name
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaExecutionPolicyBaseName:
    Default: lambda-function-policy-name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  ###################################### DynamoDB Table ############################################
  DynamoDBTableBaseName:
    Default: random-string
    Description: "The Name Of The Dynamodb Table Used For Iterating Using Step Function Map State."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter."
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: "sns-topic"
    Description: "The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 8
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 8 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ###################################### SQS Queue #################################################
  SQSQueueBaseName:
    Default: "queue"
    Description: "The Base Name Of The Sqs Queue. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 5
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 5 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  SQSDeadLetterQueueBaseName:
    Default: "dead-letter-queue"
    Description: "The Base Name Of The Dead Letter Queue. The Region And Environment Will Be Added As Suffix By The Template."
    Type: String
    MinLength: 5
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 5 and 40, must contain only lowercase letter, number, dash, dot and should start with a letter."
  ########################################### State Machine #############################################
  StepFunctionExecutionRoleBaseName:
    Default: step-function-role
    Description: Step Function Execution Role Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  StepFunctionExecutionPolicyBaseName:
    Default: step-fucntion-policy
    Description: Step Function Execution Policy Name
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: "[a-zA-Z0-9-]*"
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  # StepFunctionName:
  #   Default: step-function-name
  #   Description: Step Function Execution Policy Name
  #   Type: String
  #   MinLength: 5
  #   MaxLength: 50
  #   AllowedPattern: "[a-zA-Z-]*"
  #   ConstraintDescription: The length should be between 5 and 50, must contain only lowecase letters, numbers and hyphen (-).
Resources:

  #################################### Lambda Execution Role ##########################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${LambdaExecutionRoleBaseName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-${LambdaExecutionPolicyBaseName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-${LambdaFunctionOneBaseName}-${Environment}-${AWS::Region}:*'
                - !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-${LambdaFunctionTwoBaseName}-${Environment}-${AWS::Region}:*'
            - Sid: AllowDynamoDBPutAndGetItem
              Effect: Allow
              Action: 
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !Sub 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}-${DynamoDBTableBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowSNSPublishMessage
              Effect: Allow
              Action: 
                - sns:Publish
              Resource: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SNSTopicBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowKMSDecrypt
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
            - Sid: AllowSQSReadWriteDelete
              Effect: Allow
              Action: 
                - sqs:ReceiveMessage
                - sqs:SendMessage
                - sqs:DeleteMessage
              Resource: 
              - !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SQSQueueBaseName}-${Environment}-${AWS::Region}'
              - !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SQSDeadLetterQueueBaseName}-${Environment}-${AWS::Region}'
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment

  ################################ State Machine Execution Role #################################
  StepFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${StepFunctionExecutionRoleBaseName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
      Policies:
        - PolicyName: !Sub '${ProjectName}-${StepFunctionExecutionPolicyBaseName}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowKMSEncryptDecrypt
              Effect: Allow
              Action: 
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:GenerateDataKeyPair
              Resource: !Sub 'arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${KmsMasterKeyId}'
            - Sid: AllowKSQSSendMessage
              Effect: Allow
              Action: 
              - sqs:SendMessage
              - sqs:PurgeQueue
              Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SQSQueueBaseName}-${Environment}-${AWS::Region}'
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
              - logs:CreateLogDelivery
              - logs:CreateLogStream
              - logs:GetLogDelivery
              - logs:UpdateLogDelivery
              - logs:DeleteLogDelivery
              - logs:ListLogDeliveries
              - logs:PutLogEvents
              - logs:PutResourcePolicy
              - logs:DescribeResourcePolicies
              - logs:DescribeLogGroups
              Resource: "*"
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: EnvironmentName
          Value: !Ref Environment
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
  StepFunctionExecutionRoleArn:
    Description: The Arn of the Step Function Execution Role
    Value: !GetAtt StepFunctionExecutionRole.Arn